bunch of changes

diff --git a/mitro/mitro_bringup/daemons/ps3joy b/mitro/mitro_bringup/daemons/ps3joy
--- a/mitro/mitro_bringup/daemons/ps3joy
+++ b/mitro/mitro_bringup/daemons/ps3joy
@@ -1,36 +1,82 @@
-#!/bin/bash
-DAEMON_PATH=/opt/ros/hydro/lib/ps3joy
-DAEMON=$DAEMON_PATH/ps3joy.py
-DAEMON_OPTS=""
+### BEGIN INIT INFO
+# Provides:          ps3joy
+# Required-Start:    
+# Required-Stop:     
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: starts instance of ps3joy.py
+# Description:       starts instance of pd3joy.py
+### END INIT INFO
+
+############### EDIT ME ##################
+
+#APP_PATH=""
+
+. /opt/ros/indigo/setup.sh
+export ROS_HOME=/root
+
+# path to daemon
+DAEMON=/opt/ros/indigo/lib/ps3joy/ps3joy.py
+
+# startup args
+DAEMON_OPTS="--inactivity-timeout=900 --redirect-output=/var/log/ps3joy.log"
+
+# script name
 NAME=ps3joy
-DESC="PS3 Controller Driver" 
+
+# app name
+DESC=ps3joy
+
 RUN_AS=root
+
 PID_FILE=/var/run/ps3joy.pid
- ############### END EDIT ME ##################
+
+############### END EDIT ME ##################
+
 test -x $DAEMON || exit 0
+
 set -e
+
 case "$1" in
-    start)
+  start)
         echo -n "Starting $DESC: "
-        start-stop-daemon -d $DAEMON_PATH -c $RUN_AS --start --background --pidfile $PID_FILE  --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
-        echo "$NAME."
+
+        start-stop-daemon -c $RUN_AS --start --background --pidfile $PID_FILE  --make-pidfile -a $DAEMON -- $DAEMON_OPTS
+
+        if [ $? ]; then
+            echo "[OK]"
+        else
+            echo "[FAILED]"
+        fi
+
         ;;
-    stop)
+  stop)
         echo -n "Stopping $DESC: "
         start-stop-daemon --stop --pidfile $PID_FILE
-        echo "$NAME."
+        if [ $? ]; then
+            echo "[OK]"
+        else
+            echo "[FAILED]"
+        fi
         ;;
-    restart|force-reload)
+
+  restart|force-reload)
         echo -n "Restarting $DESC: "
-        start-stop-daemon --stop --pidfile $PID_FILE
+        start-stop-daemon --stop --oknodo --pidfile $PID_FILE
         sleep 1
-        start-stop-daemon -d $DAEMON_PATH -c $RUN_AS --start --background --pidfile $PID_FILE  --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
-        echo "$NAME."
+        start-stop-daemon -c $RUN_AS --start --background --pidfile $PID_FILE  --make-pidfile -a $DAEMON -- $DAEMON_OPTS
+        if [ $? ]; then
+            echo "[OK]"
+        else
+            echo "[FAILED]"
+        fi
+
         ;;
-    *)
+  *)
         N=/etc/init.d/$NAME
         echo "Usage: $N {start|stop|restart|force-reload}" >&2
         exit 1
         ;;
 esac
+
 exit 0
